.github/workflows/container-image.yml

Images are currently being pushed to `ghcr.io/spinkube/spinkube/runtime-class-manager`. This PR removes the redundant `spinkube`.

fix redundant image name

---

.github/workflows/container-image.yml
.github/workflows/installer-build.yml
.github/workflows/manager-build.yml
.github/workflows/release.yml
.github/workflows/sbom.yml
.github/workflows/sign-image.yml

Automatically build node installer image

---

.github/dependabot.yml

Includes `/images/installer` in the dependabot config.
Also changes the label dependabot adds to PRs to `area/dependencies` to match the config for release drafter.

Include node-installer Dockerfile in dependabot config

---

.github/workflows/container-image.yml
.github/workflows/helm-chart-release.yml
.github/workflows/installer-build.yml
.github/workflows/manager-build.yml
.github/workflows/sbom.yml
.github/workflows/sign-image.yml

Reduce the default permissions of various workflows according to recommendations by the ossf scorecard.
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/26
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/24
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/15
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/11
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/8
- https://github.com/spinkube/runtime-class-manager/security/code-scanning/7

Harden GitHub actions

---

go.mod
go.sum

Update golang.org/x/net to v0.23.0 to fix https://osv.dev/vulnerability/GO-2024-2687
Go version has already been updated to 1.22.2, but x/net is still at the affected 0.22.0.

update golang.org/x/net to v0.23.0

---

.github/workflows/ci.yml
Makefile
api/v1alpha1/shim_types.go
config/crd/bases/runtime.kwasm.sh_shims.yaml
internal/controller/shim_controller.go

This is a follow up from https://github.com/spinkube/runtime-class-manager/pull/46, it addresses the comments left inside of the review.
Please forgive me for having created a unique PR, if you want I can split each commit into separate PRs.
These are the changes done:
- chore(deps): update golangci-lint
- refactor: replace occurrences of KWasm
- fix: attempt to install shim on all nodes
- refactor: remove unneeded code
- refactor: define rollout strategy type and use constants
- fix: not all rollout strategies are implemented yet

Various fixes

---

.github/dependabot.yml
.github/workflows/downloader-build.yml
.vscode/launch.json
cmd/node-installer/uninstall.go
config/samples/test_shim_spin.yaml
images/downloader/Dockerfile
images/downloader/download_shim.sh
internal/controller/shim_controller.go
internal/shim/uninstall.go
internal/shim/uninstall_test.go

1. This PR makes sure we use the node-installer for the install job.
2. The PR adds a "shim-downloader" image. The idea is to use the downloader as initContainer: this makes the download & unzip procedure customizable to make shim downloading configurable.
3. This PR adds the configuration required to distinguish "install" and "uninstall" jobs
Addresses #52
```bash
make kind
CONTROLLER_NAMESPACE="default" \
SHIM_DOWNLOADER_IMAGE="ghcr.io/spinkube/shim-downloader:latest-feat-add_shim_downloader" \
SHIM_NODE_INSTALLER_IMAGE="ghcr.io/spinkube/node-installer:latest-feat-add_shim_downloader" \
go run -ldflags "${LDFLAGS}" ./cmd/rcm/main.go
```
```bash
kubectl apply -f ./config/samples/test_shim_spin.yaml
```
Two jobs will be scheduled on nodes with label `spin=true`
* …

feat: implement install and uninstall flow

---

internal/controller/shim_controller.go

Fixes setting the runtimeclass name.  Previously the shim name was used.  This now updates to use the runtimeclass name specified in the corresponding section of the Shim resource.
N/A

fix(shim_controller.go): set runtimeclass name correctly

---

config/rbac/role.yaml
internal/controller/job_controller.go

- Updates the job api group to batch for correct RBAC
Note: I'm not yet able to fully test via the `make build deploy` flow as RBAC issues remain.  Next up are node permissions, which will require a rewrite of node_controller.go.  

fix(rbac): change job api group to batch

---

CONTRIBUTING.md
PROJECT
config/default/kustomization.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_client_clusterrole.yaml
config/rbac/auth_proxy_role.yaml
config/rbac/auth_proxy_role_binding.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/leader_election_role.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml
config/rbac/shim_editor_role.yaml
config/rbac/shim_viewer_role.yaml
config/samples/test_shim_lunatic.yaml
config/samples/test_shim_slight.yaml
config/samples/test_shim_spin.yaml
config/samples/test_shim_wws.yaml
tilt-settings.yaml.example

Replaces "kwasm-operator" with "runtime-class-manager"
(A few other spots relating to the forthcoming helm chart were updated in the [corresponding PR](https://github.com/spinkube/runtime-class-manager/pull/204); see https://github.com/spinkube/runtime-class-manager/pull/204/commits/37c49369bf8ddb689e8dc8ca0d79866eb9d5f05a and https://github.com/spinkube/runtime-class-manager/pull/204/commits/f5b00e6164ce79a6af1df77bab20485391b60ca0)

ref(*): s/kwasm-operator/runtime-class-manager

---

.github/workflows/ci.yml
.github/workflows/helm-chart-smoketest.yml
testdata/apps/spin-app.yaml

Adds initial helm chart test automation using a KinD cluster.
Ref https://github.com/spinkube/runtime-class-manager/issues/48

ci(.github): add helm chart smoketest workflow

---

Makefile
config/crd/bases/runtime.kwasm.sh_shims.yaml

- Bumps controller-tools to the latest [v0.16.3 release](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.3)
- The motivation to bump beyond the previous v0.13.0 is because I was unable to build with my local go version (v1.23.x), hitting https://github.com/kubernetes-sigs/controller-tools/issues/880
- I'm not necessarily attached to v0.16.3 specifically, so welcome alternatives
- Includes controller-gen updates to a few files in `config`
- These _seem_ to be fairly innocuous, but could use a close look
- Includes some description re-formatting and re-wording and RBAC consolidation
Note: I'm not yet able to fully test via the `make build deploy` flow as RBAC issues remain.
- job RBAC fix: https://github.com/spinkube/runtime-class-manager/pull/224
- this PR may need …

ref(*): bump controller-gen to v0.16.3; config updates

---

.github/workflows/helm-chart-release.yml
.github/workflows/release.yml
Makefile
deploy/helm/Chart.yaml
deploy/helm/README.md
deploy/update-chart-versions.sh

- Update the helm-chart-release.yml workflow to publish to the ghcr.io registry (e.g. `ghcr.io/spinkube/charts/runtime-class-manager`)
- Per description on https://github.com/spinkube/runtime-class-manager/issues/236, this moves from publishing the chart via a chart-releaser GH action (which updates a chart index.yaml via GH pages) and instead publishes it to an OCI registry (ghcr.io)
- See runs on fork for examples: [main](https://github.com/vdice/runtime-class-manager/actions/runs/11940464722) and [v0.0.1](https://github.com/vdice/runtime-class-manager/actions/runs/11940470112)
- GH Release: https://github.com/vdice/runtime-class-manager/releases/v0.0.1
- Package listing: https://github.com/vdice/runtime-class-manager/pkgs/container/charts%2Fruntime-class-manager
- Chart can then be …

ci(*): update helm chart releasing

---

deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml
internal/controller/shim_controller.go

With this PR, users can specify the `TTLSecondsAfterFinished` when deploying the runtime-class-manager chart by setting the `rcm.nodeInstallerJob.ttl` value.
If the value is not set by the user or `0` the controller will not set the corresponding property on Job spec.
closes #199

Allow users to configure TTL for Installer Job

---

.github/workflows/release.yml

- Removes the step attempting to get the latest release
We'd need a first release for this to succeed (otherwise it fails with a 404).  If we're certain we'll want this step in the future and we'll use the output it provides, I'm happy to update this PR to just comment it out for now.

ci(release.yml): rm unused latest release step

---

.github/workflows/release.yml

- Add the [shim-downloader](https://github.com/spinkube/runtime-class-manager/tree/main/images/downloader) image build/push to release.yml

ci(release.yml): add shim-downloader to workflow

---

cmd/node-installer/detect.go
cmd/node-installer/detect_test.go

This PR was created to address the following issue:
There may be scenarios where both a default containerd file exists (eg at `/etc/containerd/config.toml`) as well as a K8s-distro specific location (eg at `/etc/k0s/containerd.toml` for K0s).  A common example case is installing a specific K8s distro directly on to a host (VM or otherwise) that already has the system containerd installed.
In the original distro detection logic, a map is used to see if a containerd config exists at a known/supported location; if it does, the distro is determined accordingly.  However, maps in Golang are unordered.  This means the default config may be returned prior to recognizing that there is a distro-specific config also on the host (eg K0s, MicroK8s, etc).
In this PR, I've split out the default …

fix(detect.go): check default location only after distro-specific

---

.github/workflows/helm-chart-smoketest.yml
images/downloader/download_shim.sh

- Updates the helm install smoke test with more k8s flavors!  Here we add minikube, microk8s and k3d
- Since they run in parallel, I figured running all cases both on PRs and merges to main is fine for now -- thoughts?
These distros all had GH actions ready-to-use.  For other distros we'd like to cover under test (k0s, etc), we could either craft a reusable action in-house and stick to the same matrix-based approach added here... or maybe break out into separate workflows.
- (See [successful runs on fork](https://github.com/vdice/runtime-class-manager/actions/runs/11861100389) which incorporates PR#264 alongside this commit)
Ref https://github.com/spinkube/runtime-class-manager/issues/48

ci(.github): update helm-chart-smoketest with more k8s variations

---

.github/workflows/helm-chart-smoketest.yml
config/samples/test_shim_spin.yaml

Bumps the containerd-shim-spin version to [v0.19.0](https://github.com/spinframework/containerd-shim-spin/releases/tag/v0.19.0)

chore(*): bump spin shim to v0.19.0

---

.github/workflows/helm-chart-smoketest.yml
internal/containerd/configure.go
internal/containerd/configure_test.go
testdata/node-installer/containerd/1.x/etc/containerd/config.toml
testdata/node-installer/containerd/2.x/etc/containerd/config.toml

Updates generateConfig to support containerd 2.x (or, more accurately, containerd config syntax version 3).  More details at https://github.com/containerd/containerd/blob/release/2.0/docs/cri/config.md
Closes https://github.com/spinframework/runtime-class-manager/issues/371

feat(containerd): support 2.x

---

.github/workflows/helm-chart-smoketest.yml
images/installer/Dockerfile
internal/containerd/restart_unix.go
internal/containerd/restart_unix_test.go
internal/preset/preset.go

Adds K8s distro-specific restarters to ameliorate the behavior mentioned in https://github.com/spinframework/runtime-class-manager/issues/140.*
* The asterisk is that the `k0s` and `k3d` distros still see the same behavior, despite attempted improvements.  (Definite follow-up/rabbit hole fodder.)
However, I'm proposing we move forward with the functionality here for a few reasons:
1. K8s distro-specific restart logic could prove useful in other ways in the future and this lays the foundation for adding/amending them.
2. The `Unknown` container termination behavior _has_ been fixed for `kind`, `k3s`, `rke2`, `minikube` and `AKS`, out of the k8s distros I tested.  Also, a check has been added to our helm smoke test, which currently vets the fix for  `minikube`, `kind` and `microk8s` (we can …

feat(*): add K8s distro-specific restarters; update default restarter

---

internal/controller/shim_controller.go

Noticed this unused env var supplied to the node-installer's provisioner container (as opposed to its downloader init container).  Seems like it should be removed.

chore(shim_controller.go): remove unused SHIM_FETCH_STRATEGY env var

---

Makefile

feat: add build/push targets for shim-downloader and node-installer images
fix: export env vars for both images for the `make run` target
Ref https://github.com/spinframework/runtime-class-manager/pull/387#issuecomment-2961578022 re: the fix

fix/feat(Makefile): add downloader and installer build targets; supply to make run

---

Makefile

😅 follow-up fix for https://github.com/spinframework/runtime-class-manager/pull/403

fix(Makefile): use correct env var for node installer image
